// <auto-generated />
namespace WebApi_Emp3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addEmp_ID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addEmp_ID));
        
        string IMigrationMetadata.Id
        {
            get { return "202110150707209_addEmp_ID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
